// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm-001utVlmoCkwvW99YDpBq5gLM-5wUk',
    appId: '1:350904435864:web:cb474146891ac0536f3ced',
    messagingSenderId: '350904435864',
    projectId: 'remedi-54c75',
    authDomain: 'remedi-54c75.firebaseapp.com',
    storageBucket: 'remedi-54c75.firebasestorage.app',
    measurementId: 'G-3JCSPC2WNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsABCo-DWkhvJrIO7Pr5nZJbKVbNK9tTM',
    appId: '1:350904435864:android:2d5e77d13cf5cee46f3ced',
    messagingSenderId: '350904435864',
    projectId: 'remedi-54c75',
    storageBucket: 'remedi-54c75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOJyFEZ2-DnLPcRc3qzZ4n1QndHUYfgw4',
    appId: '1:350904435864:ios:ae8ed26bdec8f5cd6f3ced',
    messagingSenderId: '350904435864',
    projectId: 'remedi-54c75',
    storageBucket: 'remedi-54c75.firebasestorage.app',
    iosBundleId: 'com.example.medicationReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOJyFEZ2-DnLPcRc3qzZ4n1QndHUYfgw4',
    appId: '1:350904435864:ios:ae8ed26bdec8f5cd6f3ced',
    messagingSenderId: '350904435864',
    projectId: 'remedi-54c75',
    storageBucket: 'remedi-54c75.firebasestorage.app',
    iosBundleId: 'com.example.medicationReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm-001utVlmoCkwvW99YDpBq5gLM-5wUk',
    appId: '1:350904435864:web:dd8c36fcaa25829d6f3ced',
    messagingSenderId: '350904435864',
    projectId: 'remedi-54c75',
    authDomain: 'remedi-54c75.firebaseapp.com',
    storageBucket: 'remedi-54c75.firebasestorage.app',
    measurementId: 'G-VJVVHCCRN8',
  );
}
